### ISSUE TITLE
README image is broken

### ISSUE THREAD

**Issue by chrisvdp** [emberjs/ember#2]
https://emberjs.com/images/brand/ember_Ember-Light-e42a2b30.png returns 404

**Comment by ef4** [comment]
This repo isn't actually used for anything, see https://github.com/emberjs/ember.js instead.

**Comment by wagenet** [comment]
Should probably just link to the correct repo, right?

**Comment by NullVoxPopuli** [comment]
Closed by https://github.com/emberjs/ember/pull/7
